# Site settings
title: calm coffee
email: rjameskemp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog dedicated to decaf coffee.  Especially those that are transitioning from regular.
  Perfect for pregnant folks, folks with medical issues, and just about any type of folk interested interested
  decaf coffee (mostly from Colorado).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://calm.coffee/" # the base hostname & protocol for your site
twitter_username: _robkemp
github_username:  robkemp

# Build settings
markdown: kramdown
